name: gatk-somatic
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core GATK and genomic analysis tools
  - gatk4=4.2.4.1                # GATK toolkit (Mutect2, FilterMutectCalls)
  - bwa=0.7.18                   # Genome alignment tool
  - samtools=1.3.1               # BAM/CRAM file processing
  
  # Quality control tools
  - fastp=0.23.2                 # Read quality control
  
  # Variant annotation
  - ensembl-vep=105              # Variant Effect Predictor (functional annotation)

  # Variant calling
  - manta=1.6.0                  # Structural variant caller
  - strelka2=2.9.10              # Somatic variant caller
  
  # General utilities
  - python3=3.6.8                # Python3 for any helper script
  - python2=3.7.5                # Python2 for manta/strelka2
  - bash=4.2.46                  # Bash shell for pipeline scripts
  - openjdk=1.8.0               # Java runtime (required for GATK/Picard)


 
